name: cli-node-oclif_ci

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    paths:
      # trigger build when shared scripts change
      - "src/scripts/**"
      # run this build when this file changes
      - ".github/workflows/cli-node-oclif_ci.yml"
      # run this build when the source code changes
      - "src/cli/node/oclif/**"

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      CI: true
      PROJECT_PATH: ./src/cli/node/oclif

    steps:
      - uses: actions/checkout@v2

      - name: check
        # change to the tutorial directory
        working-directory: ${{env.PROJECT_PATH}}
        run: make check

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: ${{env.PROJECT_PATH}}
          file: ${{env.PROJECT_PATH}}/Dockerfile
          push: false
