name: cli-node-oclif_cd

on:
  schedule:
    # run every day at midnight UST
    - cron: "0 0 * * *"
  push:
    branches: ["main"]
    paths:
      # trigger build when shared scripts change
      - "src/scripts/**"
      # run this build when this file changes
      - ".github/workflows/cli-node-oclif_cd.yml"
      # run this build when the source code changes
      - "src/cli/node/oclif/**"

jobs:
  install:
    runs-on: ubuntu-latest

    env:
      CI: true
      PROJECT_PATH: ./src/cli/node/oclif

    steps:
      - uses: actions/checkout@v2

      - name: check
        # change to the tutorial directory
        working-directory: ${{env.PROJECT_PATH}}
        run: make check

      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - uses: docker/build-push-action@v2
        with:
          context: ${{env.PROJECT_PATH}}
          file: ${{env.PROJECT_PATH}}/Dockerfile
          tags: ourchitecture/cli:latest,ourchitecture/cli-oclif:latest
          push: true
