name: "commitlint"

on: pull_request

jobs:
  build:
    env:
      CI: true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # https://github.com/actions/checkout#checkout-v2
          # "Only a single commit is fetched by default, for the ref/SHA that
          #  triggered the workflow. Set fetch-depth: 0 to fetch all history
          #  for all branches and tags."
          fetch-depth: 0

      - name: commitlint
        run: make commitlint commit-count=${{ github.event.pull_request.commits }}
