name: docker-devops-java_ci

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    paths:
      # run this build when this file changes
      - ".github/workflows/docker-devops-java_ci.yml"
      # run this build when the source code changes
      - "src/docker/devops/java/**"

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: ./src/docker/devops/java

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/build-push-action@v2
        with:
          context: ${{env.PROJECT_PATH}}
          file: ${{env.PROJECT_PATH}}/Dockerfile
          push: false
