name: docker-devops-az-java_cd

on:
  workflow_run:
    workflows: ["docker-devops-java_cd"]
    branches: ["main"]
    types: ["completed"]
  push:
    branches: ["main"]
    paths:
      # run this build when this file changes
      - ".github/workflows/docker-devops-az-java_cd.yml"
      # run this build when the source code changes
      - "src/docker/devops/az-java/**"

jobs:
  install:
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: ./src/docker/devops/az-java

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - uses: docker/build-push-action@v2
        with:
          context: ${{env.PROJECT_PATH}}
          file: ${{env.PROJECT_PATH}}/Dockerfile
          tags: ourchitecture/devops-az-java:latest
          push: true
