name: docker-devops-node_cd

on:
  schedule:
    # run every day at midnight UST
    - cron: "0 0 * * *"
  workflow_run:
    workflows: ["docker-devops-ubuntu_cd"]
    branches: ["main"]
    types: ["completed"]
  push:
    branches: ["main"]
    paths:
      # run this build when this file changes
      - ".github/workflows/docker-devops-node_cd.yml"
      # run this build when the source code changes
      - "src/docker/devops/node/**"

jobs:
  install:
    runs-on: ubuntu-latest

    env:
      PROJECT_PATH: ./src/docker/devops/node

    steps:
      - uses: actions/checkout@v2
      - uses: docker/setup-qemu-action@v1
      - uses: docker/setup-buildx-action@v1
      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PAT }}
      - uses: docker/build-push-action@v2
        with:
          context: ${{env.PROJECT_PATH}}
          file: ${{env.PROJECT_PATH}}/Dockerfile
          tags: ourchitecture/devops-node:latest
          push: true
