name: tutorials_java-azure_infra_ci

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    paths:
      # trigger build when shared scripts change
      - "src/scripts/**"
      # run this build when this file changes
      - ".github/workflows/tutorials_java-azure_infra_ci.yml"
      # run this build when the source code changes
      - "src/tutorials/java/azure/infrastructure/**"

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      CI: true
      PROJECT_PATH: ./src/tutorials/java/azure/infrastructure

    steps:
      - uses: actions/checkout@v2

      - name: check
        # change to the tutorial directory
        working-directory: ${{env.PROJECT_PATH}}
        run: make check
