name: tutorials_node-azure_app_cd

on:
  push:
    branches: ["main"]
    paths:
      # trigger build when shared scripts change
      - "src/scripts/**"
      # run this build when this file changes
      - ".github/workflows/tutorials_node-azure_app_cd.yml"
      # run this build when the source code changes
      - "src/tutorials/node/azure/app/**"

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      CI: true
      PROJECT_PATH: ./src/tutorials/node/azure/app

    steps:
      - uses: actions/checkout@v2

      - name: install
        # change to the tutorial directory
        working-directory: ${{env.PROJECT_PATH}}
        env:
          ENV_FILE: .env
        run: |
          set -e

          cat >./${{env.ENV_FILE}} <<EOF
          ARM_SUBSCRIPTION_ID=${{secrets.ARM_SUBSCRIPTION_ID}}
          ARM_TENANT_ID=${{secrets.ARM_TENANT_ID}}
          ARM_CLIENT_ID=${{secrets.ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET=${{secrets.ARM_CLIENT_SECRET}}
          ARM_RESOURCE_GROUP=${{secrets.ARM_RESOURCE_GROUP}}
          ARM_APP_NAME=${{secrets.ARM_APP_NAME}}
          EOF

          make install
