name: tutorials-terraform-azure-backend-maintain_cd

on:
  push:
    branches: ["main"]
    paths:
      # trigger build when shared scripts change
      - "src/scripts/**"
      # run this build when this file changes
      - ".github/workflows/tutorials-terraform-azure-backend-maintain_cd.yml"
      # run this build when the source code changes
      - "src/tutorials/terraform/azure/backend/maintain/**"

jobs:
  install:
    runs-on: ubuntu-latest

    env:
      CI: true
      PROJECT_PATH: ./src/tutorials/terraform/azure/backend/maintain

    steps:
      - uses: actions/checkout@v2

      - name: install
        # change to the tutorial directory
        working-directory: ${{env.PROJECT_PATH}}
        env:
          ENV_FILE: .env
          TF_VAR_FILE: my.tfvars
        run: |
          set -e

          cat >./${{env.ENV_FILE}} <<EOF
          ARM_SUBSCRIPTION_ID=${{secrets.ARM_SUBSCRIPTION_ID}}
          ARM_TENANT_ID=${{secrets.ARM_TENANT_ID}}
          ARM_CLIENT_ID=${{secrets.ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET=${{secrets.ARM_CLIENT_SECRET}}
          ARM_TERRAFORM_BACKEND_RESOURCE_GROUP=${{secrets.ARM_TERRAFORM_BACKEND_RESOURCE_GROUP}}
          ARM_TERRAFORM_BACKEND_STORAGE_ACCOUNT=${{secrets.ARM_TERRAFORM_BACKEND_STORAGE_ACCOUNT}}
          ARM_TERRAFORM_BACKEND_CONTAINER=${{secrets.ARM_TERRAFORM_BACKEND_CONTAINER}}
          ARM_TERRAFORM_BACKEND_KEY=backend.tfstate
          EOF

          cat >./${{env.TF_VAR_FILE}} <<EOF
          resource_group_name = "${{secrets.ARM_TERRAFORM_BACKEND_RESOURCE_GROUP}}"
          resource_group_location = "East US"
          storage_name = "${{secrets.ARM_TERRAFORM_BACKEND_STORAGE_ACCOUNT}}"
          storage_id_tag_value = "st-our-tfstate"
          storage_container_name = "tfstate"
          EOF

          make clean format install

          rm -f ${{env.ENV_FILE}} ${{env.TF_VAR_FILE}}
