name: tutorials-terraform-azure-storage_account

on:
  push:
    paths:
      # trigger build when shared scripts change
      - "src/scripts/**"
      # run this build when this file changes
      - ".github/workflows/tutorials-terraform-azure-storage_account.yml"
      # run this build when the source code changes
      - "src/tutorials/terraform/azure/storage-account/**"

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      CI: true
      PROJECT_PATH: ./src/tutorials/terraform/azure/storage-account

    steps:
      - uses: actions/checkout@v2

      - name: check
        # change to the tutorial directory
        working-directory: ${{env.PROJECT_PATH}}
        run: make check
