name: tutorials-terraform-azure-backend-maintain

on:
  pull_request_target:
    types:
      - opened
      - edited
      - synchronize
    paths:
      # trigger build when shared scripts change
      - "src/scripts/**"
      # run this build when this file changes
      - ".github/workflows/tutorials-terraform-azure-backend-maintain.yml"
      # run this build when the source code changes
      - "src/tutorials/terraform/azure/backend/maintain/**"

jobs:
  check:
    runs-on: ubuntu-latest

    env:
      CI: true
      PROJECT_PATH: ./src/tutorials/terraform/azure/backend/maintain

    steps:
      - uses: actions/checkout@v2

      - name: check
        # change to the tutorial directory
        working-directory: ${{env.PROJECT_PATH}}
        run: make check

      - name: install
        # change to the tutorial directory
        working-directory: ${{env.PROJECT_PATH}}
        env:
          ENV_FILE: .env
        run: |
          cat >./${{env.ENV_FILE}} <<EOF
          ARM_SUBSCRIPTION_ID=${{secrets.ARM_SUBSCRIPTION_ID}}
          ARM_TENANT_ID=${{secrets.ARM_TENANT_ID}}
          ARM_CLIENT_ID=${{secrets.ARM_CLIENT_ID}}
          ARM_CLIENT_SECRET=${{secrets.ARM_CLIENT_SECRET}}
          ARM_TERRAFORM_BACKEND_RESOURCE_GROUP=${{secrets.ARM_TERRAFORM_BACKEND_RESOURCE_GROUP}}
          ARM_TERRAFORM_BACKEND_STORAGE_ACCOUNT=${{secrets.ARM_TERRAFORM_BACKEND_STORAGE_ACCOUNT}}
          ARM_TERRAFORM_BACKEND_CONTAINER=${{secrets.ARM_TERRAFORM_BACKEND_CONTAINER}}
          ARM_TERRAFORM_BACKEND_KEY=backend.tfstate
          EOF
          make install
