name: "Tutorial: Node.js on Azure"

on:
  push:
    paths:
      # run this build when this file changes
      - ".github/workflows/tutorials-node-hello-azure.yml"
      # run this build when the source code changes
      - "src/tutorials/node-hello-azure/**"

jobs:
  test:
    name: Test Terraform

    env:
      CI: true
      PROJECT_PATH: ./src/tutorials/node-hello-azure

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build
        run: make init
